### PR TITLE
brd value change to uint32

### PR DESCRIPTION
**Pull request by gillespilloudwyres**
use uint32 instead of uint8 for Board values.

### CODE REVIEW

**Comment by gillespilloudwyres** [comment]
in reference of #104 issue

**Comment by brocaar** [comment]
Thank @gillespilloudwyres 

* You mentioned that the Protobuf `Board` field is of type `uint32`. In that case you don't have to cast the fields (e.g. `Brd:  uint32(frame.TxInfo.Board)` could simply be `Brd: frame.TxInfo.Board`).
* Could you install a Go plugin for your editor? That will (usually) automatically format the source-code :slightly_smiling_face: E.g. for VSCode there is: https://github.com/Microsoft/vscode-go. This is not a big issue, but it helps to keep the code formatted.

**Comment by brocaar** [comment]
I've merged your pull-request with one change (in the legacy code, it had to be casted to an `int`): https://github.com/brocaar/lora-gateway-bridge/commit/82adc02bd11a64d48a5459f01ae429e1fcc2fdb3.

**Comment by brocaar** [comment]
Will release this as v2.7.1 and will also create packages for the Kerlink gateways: https://www.loraserver.io/lora-gateway-bridge/gateway/kerlink/

**Pull request closed without merging**
